name: humanoid_loco
channels:
  - anaconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - appdirs=1.4.4
  - blas=1.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - certifi=2024.8.30
  - cffi=1.17.1
  - cfgv=3.4.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - contourpy=1.2.0
  - cuda-version=11.3
  - cudatoolkit=11.3.1
  - cudnn=8.9.2.26
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - distlib=0.3.8
  - docker-pycreds=0.4.0
  - expat=2.6.3
  - ffmpeg=4.3
  - filelock=3.13.1
  - fontconfig=2.14.1
  - fonttools=4.51.0
  - freetype=2.12.1
  - future=0.18.3
  - giflib=5.2.2
  - gitdb=4.0.7
  - gitpython=3.1.43
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmp=6.3.0
  - gnutls=3.6.13
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=58.2
  - identify=2.5.5
  - idna=3.7
  - importlib_resources=6.4.0
  - intel-openmp=2021.4.0
  - joblib=1.4.2
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.43
  - lerc=3.0
  - libabseil=20240116.2
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libgfortran=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libglib=2.78.4
  - libgomp=14.1.0
  - libhwloc=2.8.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnsl=2.0.1
  - libpng=1.6.43
  - libpq=12.17
  - libprotobuf=3.18.3
  - libsqlite=3.46.0
  - libstdcxx=14.1.0
  - libstdcxx-ng=14.1.0
  - libtiff=4.5.1
  - libuuid=2.38.1
  - libuv=1.49.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - magma=2.5.4
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mysql=5.7.24
  - nccl=2.23.4.1
  - ncurses=6.5
  - nettle=3.6
  - ninja=1.12.1
  - nodeenv=1.7.0
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.15
  - packaging=24.1
  - pandas=2.2.2
  - pathtools=0.1.2
  - pcre2=10.42
  - pillow=10.4.0
  - pip=24.2
  - platformdirs=3.10.0
  - ply=3.11
  - pooch=1.7.0
  - pre-commit=4.0.1
  - pre_commit=4.0.1
  - promise=2.3
  - protobuf=3.18.3
  - psutil=5.9.0
  - pybind11-abi=4
  - pycparser=2.21
  - pyparsing=3.1.2
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.9.20
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - python_abi=3.9
  - pytorch=1.9.1
  - pytorch-gpu=1.9.1
  - pytz=2024.1
  - pyyaml=6.0.2
  - qt=5.15.9
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - quaternion=2023.0.4
  - readline=8.2
  - requests=2.32.3
  - scikit-learn=1.5.1
  - scipy=1.10.1
  - sentry-sdk=1.9.0
  - setproctitle=1.2.2
  - setuptools=75.1.0
  - shortuuid=1.0.13
  - sip=6.7.12
  - six=1.16.0
  - sleef=3.7
  - smmap=4.0.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - tomli=2.0.1
  - torchaudio=0.9.1
  - torchvision=0.10.1
  - tornado=6.4.1
  - tqdm=4.66.5
  - typing_extensions=4.12.2
  - tzdata=2024a
  - ukkonen=1.0.1
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - virtualenv=20.26.1
  - wandb=0.13.5
  - wheel=0.44.0
  - xz=5.4.6
  - yaml=0.2.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.6
